# Global data applies to all possible variations of progress
property:
  max_targets: 1
  effects:
  - fatigue
  - blindness

# When leveling up, the values are *added* to the fields
Level:
  1:
  	cooldown: 8.0
    damage: 2.5
    range: 4.0
  2:
    cooldown: -1.0
    damage: 1.5
  ...
  N:
    damage 0.5
    range: 1.0

# Using a capability a lot may lead to some fields gaining value, values are *added* to the fields
xp:
  10:
    damage: 0.25
    range: 0.5
  15:
    damage: 0.25
  ...
  N:
    damage: 0.5