# Global data applies to all possible variations of progress
property:
  effects:
    0:
      type: fatigue
      duration: 10s
    1:
      type: blindness
      duration: 1s
      chance: 0.1

# When leveling up, the values are *added* to the fields
level:
  1: # The values specified here are the base values
    cooldown: 8.0
    damage: 2.5
    range: 4.0
  2: # Change from level 1
    cooldown: -1.0
    damage: 1.5
  # ...
  N:
    damage: 0.5
    range: 1.0

# Using a capability a lot may lead to some fields gaining value, values are *added* to the fields
xp:
  10:
    damage: 0.25
    range: 0.5
  15:
    damage: 0.25
  # ...
  N:
    damage: 0.5
