
# In vanilla, the protection enchantment blocks everything, but screw that.
# By default, this config will not follow vanilla conventions, and instead
# require the user to select the other enchantments if they want protection
# against other elements. Protection will only protect against physical attacks.

protection_environmental:
  strength: 1.0    # The EPF factor per level
  blocks:          # All damage causes the enchantment protects against
  - blunt
  - normal
  - piercing

protection_projectile:
  strength: 2.0
  blocks:
  - blunt_projectile
  - normal_projectile
  - piercing_projectile
  - magic_projectile

protection_fire:
  strength: 2.0
  blocks:
  - fire
  - lava
  - burning

protection_explosions:
  strength: 2.0
  blocks:
  - explosion

protection_fall:
  strength: 3.0
  blocks:
  - impact
