Default:
  brown_mushroom:
    categories: fungi
  egg:
    categories: protein
  pumpkin:
    categories: berries
  red_mushroom:
    categories: fungi
  sugar:
    categories: sweets
  wheat:
    categories: grain
