
# By default all vanilla foods have the same food amounts
# and effects. The time required to eat the foods have been
# changed, however. The convention for how long it takes to
# eat food is <food amount> / 10 + 0.5 seconds.
Default:
  apple:
    categories: fruit
    food: 20.0
    ratio: 0.6
    time: 2s 10t
  baked_potato:
    ingredients: potato_item
    food: 25.0
    ratio: 1.2
    time: 3s
  beetroot:
    categories: vegetable
    food: 5.0
    ratio: 1.2
    time: 1s
  beetroot_soup:
    ingredients: beetroot
    food: 30.0
    ratio: 1.2
    time: 3s 10t
  bread:
    ingredients: wheat
    food: 25.0
    ratio: 1.2
    time: 3s
  cake_block: # cake_slice (Slice)
    ingredients: cake
    food: 10.0
    ratio: 0.2
    time: 1s 10t
  cake: # (Whole cake)
    ingredients: egg wheat sugar milk_bucket
    food: 70.0
    ratio: 0.2
    time: 7s 10t
  carrot_item: # carrot
    categories: vegetable
    food: 15.0
    ratio: 1.2
    time: 2s 10t
  chorus_fruit:
    categories: fruit
    food: 20.0
    ratio: 0.6
    time: 2s
  raw_fish-2: # clownfish
    categories: meat
    food: 5.0
    ratio: 0.2
    time: 1s
  cooked_chicken:
    ingredients: raw_chicken
    food: 30.0
    ratio: 1.2
    time: 3s 10t
  cooked_fish:
    ingredients: raw_fish
    food: 25.0
    ratio: 1.2
    time: 3s
  cooked_mutton:
    ingredients: mutton
    food: 30.0
    ratio: 1.6
    time: 3s 10t
  grilled_pork:
    ingredients: porks
    food: 40.0
    ratio: 1.6
    time: 4s 10t
  cooked_rabbit:
    ingredients: rabbit
    food: 30.0
    ratio: 1.2
    time: 3s
  cooked_fish-1: # cooked_salmon
    ingredients: raw_fish-1
    food: 30.0
    ratio: 1.6
    time: 3s 10t
  cookie:
    ingredients: wheat sugar
    food: 10.0
    ratio: 0.2
    time: 1s
  golden_apple:
    categories: fruit
    food: 20.0
    ratio: 2.4
    time: 2s 10t
    alwaysConsumable: true
    effects:
      Effect 0:
        type: regeneration
        duration: 5s
        amplifier: 2
        chance: 1.0
      Effect 1:
        type: absorption
        duration: 2m
        amplifier: 4
        chance: 1.0
  golden_apple-1:
    categories: fruit
    food: 20.0
    ratio: 2.4
    time: 2s 10t
    alwaysConsumable: true
    effects:
      Effect 0:
        type: regeneration
        duration: 20s
        amplifier: 2
        chance: 1.0
      Effect 1:
        type: absorption
        duration: 2m
        amplifier: 4
        chance: 1.0
      Effect 2:
        type: damage_resistance
        duration: 5m
        amplifier: 1
        chance: 1.0
      Effect 3:
        type: fire_resistance
        duration: 5m
        amplifier: 1
        chance: 1.0
  golden_carrot:
    categories: vegetable
    food: 20.0
    ratio: 2.4
    time: 3s 10t
  melon:
    categories: berry
    food: 10.0
    ratio: 0.6
    time: 1s 10t
  milk_bucket: # Milk is one of the special items, not much to modify here
    categories: dairy
    alwaysConsumable: true
  mushroom_soup:
    ingredients: brown_mushroom
    food: 30.0
    ratio: 1.2
    time: 3s 10t
  poisonous_potato:
    ingredients: potato_item
    food: 10.0
    ratio: 0.6
    time: 1s 10t
    effects:
      Effect 0:
        type: poison
        duration: 4s
        amplifier: 1
        chance: 0.6
  potato_item: # potato
    categories: vegetable
    food: 5.0
    ratio: 0.6
    time: 1s
  raw_fish-3: # pufferfish
    categories: meat
    food: 5.0
    ratio: 0.2
    time: 1s
    effects:
      Effect 0:
        type: hunger
        duration: 15s
        amplifier: 3
        chance: 1.0
      Effect 1:
        type: confusion
        duration: 15s
        amplifier: 2
        chance: 1.0
      Effect 2:
        type: poison
        duration: 1m
        amplifier: 4
        chance: 1.0
  potion: # Another special drink, seriously, don't even try to change the settings here
    categories: potion
    alwaysConsumable: true
  pumpkin_pie:
    ingredients: egg pumpkin sugar
    food: 40.0
    ratio: 0.6
    time: 4s 10t
  rabbit_stew:
    ingredients: cooked_rabbit carrot_item baked_potato brown_mushroom
    food: 50.0
    ratio: 1.2
    time: 5s 10t
  raw_beef:
    categories: meat
    food: 15.0
    ratio: 0.6
    time: 2s
  raw_chicken:
    categories: meat
    food: 10.0
    ratio: 0.6
    time: 1s 10t
    effects:
      Effect 0:
        type: hunger
        duration: 30s
        amplifier: 1
        chance: 0.3
  raw_fish:
    categories: meat
    food: 10.0
    ratio: 0.2
    time: 1s
  mutton: # raw_mutton
    categories: meat
    food: 10.0
    ratio: 0.6
    time: 1s 10t
  pork: # raw_porkchop
    categories: meat
    food: 15.0
    ratio: 0.6
    time: 2s
  rabbit: # raw_rabbit
    categories: meat
    food: 15.0
    ratio: 0.6
    time: 2s
  raw_fish-1: # raw_salmon
    categories: meat
    food: 10.0
    ratio: 0.2
    time: 1s 10t
  rotten_flesh:
    categories: meat
    food: 20.0
    ratio: 0.2
    time: 2s 10t
    effects:
      Effect 0:
        type: hunger
        duration: 30s
        amplifier: 1
        chance: 0.8
  spider_eye:
    categories: meat
    food: 10.0
    ratio: 1.6
    time: 1s 10t
    effects:
      Effect 0:
        type: poison
        duration: 4s
        amplifier: 1
        chance: 1.0
  cooked_beef: # steak
    ingredients: raw_beef
    food: 40.0
    ratio: 1.6
    time: 4s 10t
